// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJNmY9ShXycgeZPjH7q7UJG0cPSBKSPJY',
    appId: '1:380700042754:web:6bc4162f837ae084e7291b',
    messagingSenderId: '380700042754',
    projectId: 'dishdashapp-c5af4',
    authDomain: 'dishdashapp-c5af4.firebaseapp.com',
    storageBucket: 'dishdashapp-c5af4.firebasestorage.app',
    measurementId: 'G-WY78M44ED7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwg_OnBH-mBDPwOVPColpS0_2fSoLiq2g',
    appId: '1:380700042754:android:f048e19ecdb750b3e7291b',
    messagingSenderId: '380700042754',
    projectId: 'dishdashapp-c5af4',
    storageBucket: 'dishdashapp-c5af4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Eec5g3b2Pj1SYkbM2vN6OLXkq9F7LIM',
    appId: '1:380700042754:ios:e62a5f32a715b9a4e7291b',
    messagingSenderId: '380700042754',
    projectId: 'dishdashapp-c5af4',
    storageBucket: 'dishdashapp-c5af4.firebasestorage.app',
    iosClientId: '380700042754-aujb4jsoncj9b9gru2qopelmml0jg235.apps.googleusercontent.com',
    iosBundleId: 'com.example.electroPiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Eec5g3b2Pj1SYkbM2vN6OLXkq9F7LIM',
    appId: '1:380700042754:ios:e62a5f32a715b9a4e7291b',
    messagingSenderId: '380700042754',
    projectId: 'dishdashapp-c5af4',
    storageBucket: 'dishdashapp-c5af4.firebasestorage.app',
    iosClientId: '380700042754-aujb4jsoncj9b9gru2qopelmml0jg235.apps.googleusercontent.com',
    iosBundleId: 'com.example.electroPiTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJNmY9ShXycgeZPjH7q7UJG0cPSBKSPJY',
    appId: '1:380700042754:web:dd87d4725bd8c367e7291b',
    messagingSenderId: '380700042754',
    projectId: 'dishdashapp-c5af4',
    authDomain: 'dishdashapp-c5af4.firebaseapp.com',
    storageBucket: 'dishdashapp-c5af4.firebasestorage.app',
    measurementId: 'G-56L4MFK0YQ',
  );
}
