name: electro_pi_task
description: "A modern Task Manager application built with Flutter using Clean
  Architecture, BLoC, and Firebase. The app enables users to authenticate
  securely, manage projects, organize tasks, and track progress with a clean and
  responsive user interface."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^6.6.0
  connectivity_plus: ^7.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.2
  equatable: ^2.0.8
  firebase_auth: ^6.5.4
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  get_it: ^9.2.1
  hydrated_bloc: ^11.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
          weight: 400
        - asset: assets/fonts/DancingScript-Medium.ttf
          weight: 500
        - asset: assets/fonts/DancingScript-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 700
